# Generated by Django 5.0.2 on 2024-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=2000)),
                ('due_date', models.DateField(default='', max_length=255)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]